#line 2 "../lexer/lexer.c"

#line 4 "../lexer/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[337] =
    {   0,
        0,    0,    4,    4,    0,    0,    0,    0,  112,  110,
        6,    7,   62,   54,  110,   63,   65,   53,   98,   99,
       66,   68,  104,   67,   72,   75,   47,   48,  106,  105,
       73,   69,   74,   76,   45,   45,   45,  100,  101,   64,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,  102,   71,  103,   70,
        4,    3,  111,  111,   61,   55,   61,   56,   90,    0,
      109,    0,   78,   91,   81,   95,   96,   93,   97,   94,
       84,    0,   50,    0,    2,    0,   77,   50,   47,    0,
        0,    0,   47,   47,    0,   47,   48,   48,   48,   48,

       85,   87,   89,   88,   86,    0,   45,   45,   54,   53,
       82,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       15,   45,   45,   45,   45,   45,   45,   23,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   83,
       92,    4,    5,   60,   57,   57,   58,   60,    0,  107,
        0,   50,   50,    0,    0,    1,   50,   52,   52,   50,
        0,   49,   47,   47,   47,   47,   46,   48,   48,   48,
       48,   79,   80,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   21,   45,   45,
       25,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   58,   59,    0,
        0,   50,    0,   52,   50,   49,   49,   49,   47,   52,
       46,    0,   46,   46,   48,   45,   45,   45,    8,   45,
       10,   11,   45,   45,   45,   45,   17,   18,   45,   45,
       22,   45,   26,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   39,   45,   45,   58,    0,
       50,   52,   46,   46,    0,   51,   46,   46,   42,   45,
       45,    9,   12,   45,   45,   45,   45,   20,   45,   45,
       45,   45,   30,   45,   45,   45,   45,   45,   45,   37,
       45,   45,   41,    0,   51,   46,   45,   45,   45,   45,

       16,   19,   24,   45,   45,   29,   31,   32,   33,   34,
       35,   45,   45,   45,    0,   45,   45,   45,   14,   45,
       45,   36,   45,   45,    0,  108,   43,   45,   13,   27,
       28,   38,   40,   45,   44,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    4,    3,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    1,    1,
        1,    1,    6,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[349] =
    {   0,
        0,    0,   69,   70,   68,   71,   74,   79,  852,  853,
      853,  853,  826,  853,   87,  825,   70,  853,  853,  853,
      824,   72,  853,   76,   79,   91,  103,  107,  853,  853,
       69,  823,   80,  853,  156,  830,  119,  853,  853,  821,
      126,  189,   48,  102,   55,  127,  109,  101,  173,  113,
      145,  162,  150,   98,  174,  161,  853,  155,  853,  853,
        0,  853,  853,  827,  853,  853,  246,  853,  853,  841,
      853,  222,  853,  853,  853,  853,  853,  853,  853,  853,
      853,  826,  293,  210,  853,  839,  853,  333,  190,  239,
      250,  263,  195,  161,    0,  145,    0,  210,  209,  238,

      816,  853,  853,  853,  815,    0,  777,  821,  853,  853,
      853,  223,  231,  194,  178,  237,   77,  245,  247,  248,
      244,  236,  270,  233,  261,  287,  282,  820,  313,  299,
      298,  300,  316,  291,  317,  302,  332,  319,  339,  853,
      853,    0,  853,  853,  853,  178,  307,    0,  382,  853,
      379,  353,  853,  393,  833,  853,    0,    0,  402,    0,
      385,  394,  283,  853,  800,  780,  403,  335,  853,  782,
      758,  853,  853,  371,  377,  373,  402,  407,  327,  408,
      410,  387,  413,  416,  417,  418,  419,  794,  424,  425,
      768,  428,  427,  429,  314,  430,  435,  436,  433,  437,

      439,  438,  445,  443,  451,  452,  456,  455,    0,  477,
      484,  487,  492,  495,  500,  504,    0,  853,  853,  853,
      497,  526,  447,  455,  853,  468,  470,  476,  767,  480,
      766,  765,  512,  520,  719,  521,  763,  762,  524,  526,
      761,  533,  760,  534,  537,  538,  539,  540,  535,  543,
      544,  545,  546,  547,  548,  759,  549,  551,  853,  610,
      663,  853,  539,  853,  550,  667,  740,  720,  755,  550,
      557,  754,  753,  668,  672,  560,  673,  752,  674,  675,
      676,  677,  751,  680,  683,  561,  679,  684,  686,  749,
      687,  689,  748,  758,  853,  853,  690,  688,  691,  693,

      746,  743,  742,  694,  701,  741,  739,  735,  732,  731,
      722,  696,  698,  697,  602,  692,  562,  702,  585,  703,
      706,  569,  708,  713,  582,  853,  567,  714,  565,  564,
      563,  471,  459,  720,  177,  853,  786,  792,  798,  801,
      803,  809,  815,  821,  169,  116,  108,  827
    } ;

static const flex_int16_t yy_def[349] =
    {   0,
      336,    1,  337,  337,  338,  338,  338,  338,  336,  336,
      336,  336,  336,  336,  339,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  340,  336,  336,   27,  336,  336,
      336,  336,  336,  336,  341,  341,  341,  336,  336,  336,
      341,  341,   42,   42,   42,   42,   42,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  336,  336,  336,  336,
      342,  336,  336,  336,  336,  336,  343,  336,  336,  339,
      336,  339,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  340,  336,  344,  336,  336,   27,   28,
       90,   91,  336,  336,  345,  336,   28,  336,  336,  336,

      336,  336,  336,  336,  336,  346,   42,  341,  336,  336,
      336,  341,  341,  341,  341,  341,   42,  341,  341,   42,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  336,
      336,  342,  336,  336,  336,  336,  336,  347,  339,  336,
      340,  340,  336,  336,  344,  336,   88,  346,  346,  346,
      336,   92,  336,  336,  336,  336,  345,  336,  336,  336,
      336,  336,  336,  341,  341,  341,  341,  341,  341,  341,
      341,   42,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  336,  347,  339,
      336,   83,  336,  336,   88,  336,   91,  336,  336,  336,
      336,  336,  336,  336,  336,  341,  341,  341,  341,  341,
      341,  341,  341,  341,   42,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  260,  336,  336,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  348,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  348,  336,  341,  341,  341,  341,
      341,  341,  341,  341,  341,    0,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336
    } ;

static const flex_int16_t yy_nxt[925] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   35,   36,   36,   37,   36,   36,   36,   38,   10,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       36,   49,   36,   50,   36,   36,   36,   36,   51,   52,
       53,   54,   55,   56,   36,   36,   36,   57,   58,   59,
       60,   62,   62,   63,   63,   63,   63,   66,   74,   68,
       66,   64,   64,   63,   68,   77,   63,   63,   63,   71,
       72,   79,  101,  102,   75,   82,   78,   83,   83,   83,

       80,   81,  120,   85,  104,  105,  116,   67,   86,  108,
       67,  121,  209,   67,  336,   87,  108,  336,   67,   88,
      158,   89,   89,   90,  109,   97,   97,   97,  110,  336,
       91,   91,   91,   92,   91,  336,  179,   93,  108,   94,
       95,   98,  336,   99,  336,  117,   91,   91,   91,   91,
       92,   91,  118,  137,  112,  113,   96,  127,  119,  114,
      100,  336,  125,  108,   94,  126,  336,   95,   99,  130,
      108,  336,  106,  167,  107,  107,  107,  336,  336,  140,
      122,  164,  123,  107,  107,  107,  107,  107,  108,  336,
      336,  124,  131,  336,  336,  165,  208,  208,  163,  107,

      107,  107,  107,  107,  107,  106,  164,  107,  107,  107,
      336,  139,  132,  133,  166,  136,  107,  107,  107,  107,
      107,  128,  134,  141,   71,  135,  336,  336,  129,  163,
      138,  164,  107,  107,  107,  107,  107,  107,  177,  336,
      149,  149,  149,  170,  168,  154,  169,  336,  176,  336,
      115,  145,  336,  336,  336,  145,  164,   90,   90,   90,
      336,  336,  171,  336,  146,  147,  106,  154,   91,   91,
       91,  169,  145,  336,  169,  336,  161,  336,  161,  174,
       91,  162,  162,  162,  178,  145,  336,  175,  180,  145,
      145,  168,  336,  186,  145,  184,  182,   91,  336,  169,

      336,  145,  181,  336,  145,  183,  145,  336,  145,  108,
      148,   83,   83,   83,  336,  336,  336,  187,  336,  164,
       84,   84,   84,  151,  152,  208,  208,  153,  154,  336,
      336,  185,  336,  336,  199,  336,   84,   84,   84,   84,
      151,  152,  189,  336,  164,  188,  153,  193,  336,  200,
      154,  157,  157,  157,  192,  336,  196,  194,  195,  202,
      158,  158,  158,  159,  160,  197,  190,  153,  201,  336,
      205,  169,  206,  191,  231,  246,  158,  158,  158,  158,
      159,  160,  198,  203,   71,  210,  153,  336,  154,  336,
      207,  204,  211,  336,  211,  336,  169,  212,  212,  212,

      149,  149,  149,  216,  216,  216,  213,  336,  213,  336,
      154,  214,  214,  214,  154,  211,  228,  211,  336,  220,
      215,  215,  215,  336,  336,  217,  336,  226,  218,  336,
      235,  227,  336,  336,  336,  336,  154,  221,  222,  223,
      336,  336,  217,  336,  336,  336,  336,  218,  108,  336,
      230,  336,  336,  336,  336,  336,  224,  236,  229,  336,
      222,  336,  240,  237,  223,  239,  232,  336,  336,  233,
      234,  238,  336,  259,  259,  336,  242,  243,  244,   71,
      241,  267,  260,  249,  336,  253,  336,  336,  247,  245,
      248,  264,  336,  250,  255,  257,  336,  256,  251,  252,

      268,  254,  261,  261,  261,  212,  212,  212,  263,  258,
      214,  214,  214,  214,  214,  214,  264,   84,  215,  215,
      215,  269,  216,  216,  216,  271,  262,  270,  336,  262,
      158,  263,  272,  264,   84,  218,  336,  336,  218,  265,
      336,  265,  336,  262,  266,  266,  266,  158,  262,  336,
      336,  336,  218,  336,  336,  336,  336,  218,  264,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  266,  266,
      266,  274,  273,  336,  276,  264,  336,  336,  336,  336,
      336,  336,  277,  336,  326,  336,  278,  284,  279,  287,
      288,  285,  289,  280,  286,  281,  282,  291,  293,  283,

      264,  336,  290,  297,  326,  328,  309,  301,  298,  292,
       70,   70,   71,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,  294,  294,  294,  294,
      294,   70,   70,   70,   70,   70,   70,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,   70,   70,
       70,   70,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,   70,   70,   70,
       70,  261,  261,  261,  336,  266,  266,  266,  336,  336,
      336,  336,  336,  336,  153,  336,  336,  153,  295,  336,

      336,  295,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  153,  336,  336,  336,  295,  153,  336,  336,  336,
      295,  303,  336,  299,  336,  300,  307,  305,  302,  336,
      336,  308,  306,  312,  311,  304,  336,  316,  336,  310,
      314,  320,  313,  317,  322,  323,  321,  336,  336,  329,
      324,  336,  318,  319,  332,  336,  327,  336,  336,  336,
      333,  330,  336,  315,  336,  336,  331,  336,  336,  336,
      336,  336,  334,  296,  296,  336,  336,  336,  336,  336,
      275,  336,  336,  336,  336,  335,   61,   61,   61,   61,
       61,   61,   65,   65,   65,   65,   65,   65,   70,   70,

       70,   70,   70,   70,   84,   84,  108,  108,  108,  142,
      336,  225,  142,  142,  142,  144,  225,  144,  144,  144,
      144,  155,  155,  155,  155,  155,  155,  325,  325,  325,
      325,  325,  325,  219,  219,  156,  336,  336,  108,  173,
      172,  156,  150,   71,  143,  111,  336,  103,   76,   73,
       69,  336,    9,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336
    } ;

static const flex_int16_t yy_chk[925] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    3,    4,    6,    5,   17,    7,
        6,    3,    4,    7,    8,   22,    3,    4,    8,   15,
       15,   24,   31,   31,   17,   25,   22,   25,   25,   25,

       24,   24,   45,   26,   33,   33,   43,    5,   26,   43,
        6,   45,  347,    7,   54,   26,   45,   48,    8,   27,
      346,   27,   27,   27,   37,   28,   28,   28,   37,   50,
       27,   27,   27,   27,   27,   37,  117,   27,  117,   27,
       27,   28,   41,   28,   28,   44,   27,   27,   27,   27,
       27,   27,   44,   54,   41,   41,   27,   48,   44,   41,
       28,   51,   47,   44,   27,   47,   53,   27,   28,   50,
       47,   28,   35,  345,   35,   35,   35,   56,   52,   58,
       46,   96,   46,   35,   35,   35,   35,   35,   46,   49,
       55,   46,   51,  335,  115,   94,  146,  146,   96,   35,

       35,   35,   35,   35,   35,   42,   96,   42,   42,   42,
      114,   56,   52,   52,   94,   53,   42,   42,   42,   42,
       42,   49,   52,   58,   72,   52,   84,   89,   49,   93,
       55,   93,   42,   42,   42,   42,   42,   42,  115,  112,
       72,   72,   72,   99,   98,   84,   98,  113,  114,  124,
       42,   67,  122,  116,   89,   67,   93,   90,   90,   90,
      121,  118,   99,  119,   67,   67,   91,   84,   91,   91,
       91,   98,   67,   90,  100,   90,   92,  125,   92,  112,
       91,   92,   92,   92,  116,   67,  123,  113,  118,   67,
       67,  100,   90,  124,   67,  122,  120,   91,  127,  100,

       90,   67,  119,  126,   67,  121,   67,  134,   67,  120,
       67,   83,   83,   83,  131,  130,  132,  125,  136,  163,
       83,   83,   83,   83,   83,  147,  147,   83,   83,  129,
      195,  123,  133,  135,  134,  138,   83,   83,   83,   83,
       83,   83,  127,  179,  163,  126,   83,  131,  137,  134,
       83,   88,   88,   88,  130,  139,  132,  131,  131,  136,
       88,   88,   88,   88,   88,  133,  129,   88,  135,  152,
      138,  168,  138,  129,  179,  195,   88,   88,   88,   88,
       88,   88,  133,  137,  149,  149,   88,  174,  152,  176,
      139,  137,  151,  175,  151,  151,  168,  151,  151,  151,

      149,  149,  149,  161,  161,  161,  154,  162,  154,  162,
      152,  154,  154,  154,  151,  159,  176,  159,  177,  167,
      159,  159,  159,  178,  180,  162,  181,  174,  162,  183,
      182,  175,  184,  185,  186,  187,  151,  167,  167,  167,
      189,  190,  162,  193,  192,  194,  196,  162,  182,  199,
      178,  197,  198,  200,  202,  201,  167,  183,  177,  204,
      167,  203,  187,  184,  167,  186,  180,  205,  206,  181,
      181,  185,  207,  208,  208,  333,  190,  192,  193,  210,
      189,  223,  210,  198,  226,  202,  227,  332,  196,  194,
      197,  224,  228,  199,  204,  206,  230,  205,  200,  201,

      223,  203,  211,  211,  211,  212,  212,  212,  224,  207,
      213,  213,  213,  214,  214,  214,  224,  212,  215,  215,
      215,  226,  216,  216,  216,  228,  214,  227,  233,  214,
      215,  221,  230,  221,  212,  216,  234,  236,  216,  222,
      239,  222,  240,  214,  222,  222,  222,  215,  214,  242,
      244,  249,  216,  245,  246,  247,  248,  216,  221,  250,
      251,  252,  253,  254,  255,  257,  270,  258,  265,  265,
      265,  234,  233,  271,  236,  263,  276,  286,  317,  331,
      330,  329,  239,  327,  325,  322,  240,  248,  242,  251,
      252,  249,  253,  244,  250,  245,  246,  255,  258,  247,

      263,  319,  254,  270,  315,  317,  286,  276,  271,  257,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  261,  261,  261,  274,  266,  266,  266,  275,  277,
      279,  280,  281,  282,  261,  287,  284,  261,  266,  285,

      288,  266,  289,  291,  298,  292,  297,  299,  316,  300,
      304,  261,  312,  314,  313,  266,  261,  305,  318,  320,
      266,  279,  321,  274,  323,  275,  284,  281,  277,  324,
      328,  285,  282,  289,  288,  280,  334,  297,  311,  287,
      292,  304,  291,  298,  312,  313,  305,  310,  309,  318,
      314,  308,  299,  300,  323,  307,  316,  306,  303,  302,
      324,  320,  301,  294,  293,  290,  321,  283,  278,  273,
      272,  269,  328,  268,  267,  256,  243,  241,  238,  237,
      235,  232,  231,  229,  191,  334,  337,  337,  337,  337,
      337,  337,  338,  338,  338,  338,  338,  338,  339,  339,

      339,  339,  339,  339,  340,  340,  341,  341,  341,  342,
      188,  171,  342,  342,  342,  343,  170,  343,  343,  343,
      343,  344,  344,  344,  344,  344,  344,  348,  348,  348,
      348,  348,  348,  166,  165,  155,  128,  108,  107,  105,
      101,   86,   82,   70,   64,   40,   36,   32,   21,   16,
       13,    9,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../lexer/lexer.l"
/*
 * ECE:466 Compilers
 * By: Guy Bar Yosef
 *
 * lexer.l - The flex file that will be
 * used to build the lexical analyzer.
 */
/* Prologue: Options and definitions */
/* flex doesn't call yywrap after end of file */
/* no default line counter, we do it ourselves */
/* setting up start states */



/* repeating patterns */
/* vars which can be accessed inside yylex() and main() */
#line 30 "../lexer/lexer.l"
	#include "lheader2.h"
	#include "lheader.h"

	int cur_line_num = 1;					/* current line number  */
	char cur_file_name[LINESIZE+1];			/* current file name    */
	char tmp[20];							/* temp helper variable */
	char strlit_buffer[MAX_STRLIT_SIZE];	/* buffer for string literals */

	/* helper pointers for exracting the line numbers and file names */
	char *helper_end, *helper_begin;    

	YYSTYPE yylval;
#line 793 "../lexer/lexer.c"
#line 794 "../lexer/lexer.c"

#define INITIAL 0
#define COMMENT 1
#define CHR_LIT 2
#define STR_LIT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "../lexer/lexer.l"

#line 46 "../lexer/lexer.l"
	/* Body: (regexp) : (embedded action) pairs */

	/* skip comments */
#line 1020 "../lexer/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 337 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 853 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 49 "../lexer/lexer.l"
{ ++cur_line_num; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "../lexer/lexer.l"
{ BEGIN COMMENT;  }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "../lexer/lexer.l"
{ ++cur_line_num; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "../lexer/lexer.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "../lexer/lexer.l"
{ BEGIN INITIAL;  }
	YY_BREAK
/* skip white spaces  */
case 6:
YY_RULE_SETUP
#line 57 "../lexer/lexer.l"
{}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 58 "../lexer/lexer.l"
{ ++cur_line_num; }
	YY_BREAK
/* tokens: keywords */
case 8:
YY_RULE_SETUP
#line 62 "../lexer/lexer.l"
{ return AUTO;     }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "../lexer/lexer.l"
{ return BREAK;    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 "../lexer/lexer.l"
{ return CASE;     }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "../lexer/lexer.l"
{ return CHAR;     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "../lexer/lexer.l"
{ return CONST;    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "../lexer/lexer.l"
{ return CONTINUE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "../lexer/lexer.l"
{ return DEFAULT;  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "../lexer/lexer.l"
{ return DO;       }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "../lexer/lexer.l"
{ return DOUBLE;   }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "../lexer/lexer.l"
{ return ELSE;     }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "../lexer/lexer.l"
{ return ENUM;     }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "../lexer/lexer.l"
{ return EXTERN;   }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "../lexer/lexer.l"
{ return FLOAT;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "../lexer/lexer.l"
{ return FOR;      }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 "../lexer/lexer.l"
{ return GOTO;     }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "../lexer/lexer.l"
{ return IF;       }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "../lexer/lexer.l"
{ return INLINE;   }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "../lexer/lexer.l"
{ return INT;      }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "../lexer/lexer.l"
{ return LONG;     }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "../lexer/lexer.l"
{ return REGISTER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "../lexer/lexer.l"
{ return RESTRICT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "../lexer/lexer.l"
{ return RETURN;   }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "../lexer/lexer.l"
{ return SHORT;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "../lexer/lexer.l"
{ return SIGNED;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "../lexer/lexer.l"
{ return SIZEOF;   }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "../lexer/lexer.l"
{ return STATIC;   }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "../lexer/lexer.l"
{ return STRUCT;   }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "../lexer/lexer.l"
{ return SWITCH;   }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "../lexer/lexer.l"
{ return TYPEDEF;  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "../lexer/lexer.l"
{ return UNION;    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "../lexer/lexer.l"
{ return UNSIGNED; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "../lexer/lexer.l"
{ return VOID;     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "../lexer/lexer.l"
{ return VOLATILE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "../lexer/lexer.l"
{ return WHILE;    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 96 "../lexer/lexer.l"
{ return _BOOL;    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 97 "../lexer/lexer.l"
{ return _COMPLEX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 98 "../lexer/lexer.l"
{ return _IMAGINARY; }
	YY_BREAK
/* identifiers */
case 45:
YY_RULE_SETUP
#line 102 "../lexer/lexer.l"
{ yylval.str.str = yytext; return IDENT; }
	YY_BREAK
/* tokens: integer constants */
case 46:
YY_RULE_SETUP
#line 106 "../lexer/lexer.l"
{
		yylval.num.types |= NUMMASK_INTGR;	
		yylval.num.val = strtol(yytext, NULL, 16);
	
		checkNumberTypes(&yylval, yytext);
		return NUMBER;
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "../lexer/lexer.l"
{		
		yylval.num.types = NUMMASK_INTGR;	
		yylval.num.val = strtol(yytext, NULL, 8);

		checkNumberTypes(&yylval, yytext);
		return NUMBER;
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 122 "../lexer/lexer.l"
{		
		yylval.num.types = NUMMASK_INTGR;
		yylval.num.val = strtol(yytext, NULL, 10);

		checkNumberTypes(&yylval, yytext);
		return NUMBER;
	}
	YY_BREAK
/* tokens: float constants */
case 49:
YY_RULE_SETUP
#line 131 "../lexer/lexer.l"
{
	char f_tmp = yytext[strlen(yytext)-1];
	if (f_tmp == 'f' || f_tmp == 'F')
		yylval.num.types = NUMMASK_FLOAT;
	else if (f_tmp == 'l' || f_tmp == 'L')
		yylval.num.types = NUMMASK_LDBLE;
	else
		yylval.num.types = NUMMASK_DOUBLE;

	yylval.num.d_val = strtod(yytext, NULL);
	return NUMBER;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "../lexer/lexer.l"
{
	char f_tmp = yytext[strlen(yytext)-1];
	if (f_tmp == 'f' || f_tmp == 'F')
		yylval.num.types = NUMMASK_FLOAT;
	else if (f_tmp == 'l' || f_tmp == 'L')
		yylval.num.types = NUMMASK_LDBLE;
	else
		yylval.num.types = NUMMASK_DOUBLE;

	yylval.num.d_val = strtod(yytext, NULL);
	return NUMBER;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 159 "../lexer/lexer.l"
{
	char f_tmp = yytext[strlen(yytext)-1];
	if (f_tmp == 'f' || f_tmp == 'F')
		yylval.num.types = NUMMASK_FLOAT;
	else if (f_tmp == 'l' || f_tmp == 'L')
		yylval.num.types = NUMMASK_LDBLE;
	else
		yylval.num.types = NUMMASK_DOUBLE;


	yylval.num.d_val = strtod(yytext, NULL);
	return NUMBER;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 173 "../lexer/lexer.l"
{
	char f_tmp = yytext[strlen(yytext)-1];
	if (f_tmp == 'f' || f_tmp == 'F')
		yylval.num.types = NUMMASK_FLOAT;
	else if (f_tmp == 'l' || f_tmp == 'L')
		yylval.num.types = NUMMASK_LDBLE;
	else
		yylval.num.types = NUMMASK_DOUBLE;


	yylval.num.d_val = strtod(yytext, NULL);
	return NUMBER;
}
	YY_BREAK
/* tokens: character & string literals */
case 53:
YY_RULE_SETUP
#line 189 "../lexer/lexer.l"
{ 	
		BEGIN CHR_LIT;

		/* zero out the string literal buffer */
		memset(strlit_buffer, 0, sizeof(strlit_buffer));
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 195 "../lexer/lexer.l"
{ 	
		BEGIN STR_LIT;

		/* zero out the string literal buffer */
		memset(strlit_buffer, 0, sizeof(strlit_buffer));
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 201 "../lexer/lexer.l"
{ 	
		yylval.str.char_val = strlit_buffer[0]; 
		BEGIN INITIAL;
		return CHARLIT;
	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 206 "../lexer/lexer.l"
{ 	
		BEGIN INITIAL;

		/* allocate space for string literal and copy it into yylval */
		if (!(yylval.str.str = malloc(yylval.str.str_size+1))) {
			fprintf(stderr, "Error allocating space for string "
									"literal: %s\n", strerror(errno));
			return -1;
		}
		memcpy(yylval.str.str, strlit_buffer, yylval.str.str_size);
		return STRING;
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 219 "../lexer/lexer.l"
{
		if (yylval.str.str_size < MAX_STRLIT_SIZE) {
			switch(yytext[1]) {
				case '\\':strlit_buffer[yylval.str.str_size] = 92; break;
				case '0': strlit_buffer[yylval.str.str_size] = 0;  break;
				case 'n': strlit_buffer[yylval.str.str_size] = 10; break;
				case 'a': strlit_buffer[yylval.str.str_size] = 7;  break;
				case 'b': strlit_buffer[yylval.str.str_size] = 8;  break;
				case 't': strlit_buffer[yylval.str.str_size] = 9;  break;
				case 'r': strlit_buffer[yylval.str.str_size] = 13; break;
				case 'f': strlit_buffer[yylval.str.str_size] = 12; break;
				case 'v': strlit_buffer[yylval.str.str_size] = 11; break;
				case '\'':strlit_buffer[yylval.str.str_size] = 39; break;
				case '"': strlit_buffer[yylval.str.str_size] = 34; break;
				case '?': strlit_buffer[yylval.str.str_size] = 63;
				default: break;
			} 
			++yylval.str.str_size;
		}
	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 240 "../lexer/lexer.l"
{
		if (yylval.str.str_size < MAX_STRLIT_SIZE) {
			long int tmp = strtol(yytext+1, NULL, 8);
			if (tmp > 255)
				tmp = 255;
			strlit_buffer[yylval.str.str_size] = tmp;
			++yylval.str.str_size;
		}
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "../lexer/lexer.l"
{
		if (yylval.str.str_size < MAX_STRLIT_SIZE) {
			yytext[0] = '0';
			long int tmp = strtol(yytext, NULL, 16);
			if (tmp > 255)
				tmp = 255;
			strlit_buffer[yylval.str.str_size] = tmp;
			++yylval.str.str_size;
		}
	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 261 "../lexer/lexer.l"
{ 
		if (yylval.str.str_size < MAX_STRLIT_SIZE) {
			fprintf(stderr, "%s:%d: Error: unrecognized character %s\n", 
										cur_file_name, cur_line_num, yytext);
			return -1;
		}
	}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 269 "../lexer/lexer.l"
{
		if (yylval.str.str_size < MAX_STRLIT_SIZE) {
			strlit_buffer[yylval.str.str_size] = yytext[0];
			++yylval.str.str_size;
		}
	}
	YY_BREAK
/* tokens: operators */
case 62:
#line 279 "../lexer/lexer.l"
case 63:
#line 280 "../lexer/lexer.l"
case 64:
#line 281 "../lexer/lexer.l"
case 65:
#line 282 "../lexer/lexer.l"
case 66:
#line 283 "../lexer/lexer.l"
case 67:
#line 284 "../lexer/lexer.l"
case 68:
#line 285 "../lexer/lexer.l"
case 69:
#line 286 "../lexer/lexer.l"
case 70:
#line 287 "../lexer/lexer.l"
case 71:
#line 288 "../lexer/lexer.l"
case 72:
#line 289 "../lexer/lexer.l"
case 73:
#line 290 "../lexer/lexer.l"
case 74:
#line 291 "../lexer/lexer.l"
case 75:
#line 292 "../lexer/lexer.l"
case 76:
YY_RULE_SETUP
#line 292 "../lexer/lexer.l"
{ return yytext[0]; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 294 "../lexer/lexer.l"
{ return DIVEQ;   }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 295 "../lexer/lexer.l"
{ return MODEQ;   }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 296 "../lexer/lexer.l"
{ return SHLEQ;   }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 297 "../lexer/lexer.l"
{ return SHREQ;   }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 298 "../lexer/lexer.l"
{ return ANDEQ;   }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 299 "../lexer/lexer.l"
{ return XOREQ;   }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 300 "../lexer/lexer.l"
{ return OREQ;    }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 301 "../lexer/lexer.l"
{ return INDSEL;  }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 302 "../lexer/lexer.l"
{ return SHL;     }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 303 "../lexer/lexer.l"
{ return SHR;     }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 304 "../lexer/lexer.l"
{ return LTEQ;    }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 305 "../lexer/lexer.l"
{ return GTEQ;    }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 306 "../lexer/lexer.l"
{ return EQEQ;    }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 307 "../lexer/lexer.l"
{ return NOTEQ;   }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 308 "../lexer/lexer.l"
{ return LOGAND;  }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 309 "../lexer/lexer.l"
{ return LOGOR;   }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 310 "../lexer/lexer.l"
{ return PLUSEQ;  }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 311 "../lexer/lexer.l"
{ return MINUSEQ; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 312 "../lexer/lexer.l"
{ return TIMESEQ; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 313 "../lexer/lexer.l"
{ return PLUSPLUS;   }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 314 "../lexer/lexer.l"
{ return MINUSMINUS; }
	YY_BREAK
/* tokens: separator characters */
case 98:
#line 319 "../lexer/lexer.l"
case 99:
#line 320 "../lexer/lexer.l"
case 100:
#line 321 "../lexer/lexer.l"
case 101:
#line 322 "../lexer/lexer.l"
case 102:
#line 323 "../lexer/lexer.l"
case 103:
#line 324 "../lexer/lexer.l"
case 104:
#line 325 "../lexer/lexer.l"
case 105:
#line 326 "../lexer/lexer.l"
case 106:
YY_RULE_SETUP
#line 326 "../lexer/lexer.l"
{ return yytext[0]; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 327 "../lexer/lexer.l"
{ return ELLIPSIS; }
	YY_BREAK
/* Preprocessor output as well as keeping track 
	   of file name and line number for error checking. */
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 332 "../lexer/lexer.l"
{
		/* get current file name */
		helper_begin = strstr(yytext, "\""); 
		helper_end = strstr(++helper_begin, "\"");
		strncpy(cur_file_name, helper_begin, (size_t)(helper_end-helper_begin));
		cur_file_name[(size_t)(helper_end-helper_begin)] = 0;

		/* get current line */
		helper_begin = strstr(yytext, " ");
		helper_end = strstr(++helper_begin, " ");
		strncpy(tmp, helper_begin, (size_t)(helper_end-helper_begin));
		cur_line_num = atoi(tmp);
	}
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 345 "../lexer/lexer.l"
{}    /* skip any other preprocessor output */
	YY_BREAK
/* error handling and reporting */
case 110:
YY_RULE_SETUP
#line 348 "../lexer/lexer.l"
{ 
		fprintf(stderr, "%s:%d: Error: unrecognized character %s\n", 
								cur_file_name, cur_line_num, yytext);
		return -1;
	}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 354 "../lexer/lexer.l"
ECHO;
	YY_BREAK
#line 1735 "../lexer/lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(CHR_LIT):
case YY_STATE_EOF(STR_LIT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 337 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 337 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 336);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 354 "../lexer/lexer.l"

	/* Epilouge: Code to be run using lexer */

